-- CreateTable
CREATE TABLE `resources` (
    `id` BIGINT UNSIGNED NOT NULL,
    `code` VARCHAR(32) NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `shortName` VARCHAR(100) NOT NULL,
    `displayName` VARCHAR(100) NOT NULL,
    `openingTime` CHAR(5) NOT NULL,
    `closingTime` CHAR(5) NOT NULL,
    `isCrossDay` BOOLEAN NOT NULL DEFAULT false,
    `resourceCategoryCode` VARCHAR(32) NOT NULL,
    `resourceTypeCode` VARCHAR(32) NOT NULL,
    `resourceStatus` VARCHAR(32) NOT NULL,
    `patternId` INTEGER NOT NULL,
    `priority` INTEGER NOT NULL DEFAULT 0,
    `dispatched` INTEGER NOT NULL DEFAULT 0,
    `resourceLinkId` BIGINT UNSIGNED NOT NULL,
    `resourceGroupId` BIGINT UNSIGNED NOT NULL,
    `bindRelatedResourceTypeCode` JSON NOT NULL,
    `currentRelatedResourceId` BIGINT UNSIGNED NULL,
    `currentRelatedResourceName` VARCHAR(100) NULL,
    `currentRelatedResourceDisplayName` VARCHAR(100) NULL,
    `latestLongitude` DECIMAL(10, 7) NULL,
    `latestLatitude` DECIMAL(10, 7) NULL,
    `latestPositionChangeTime` DATETIME(3) NULL,
    `dataSource` VARCHAR(32) NOT NULL,
    `relatedExternalId` VARCHAR(64) NOT NULL,
    `selfModifiedFlag` INTEGER NOT NULL DEFAULT 0,
    `displayed` BOOLEAN NOT NULL DEFAULT true,
    `displayOrder` INTEGER NOT NULL DEFAULT 0,
    `airportCode` VARCHAR(8) NOT NULL,
    `businessType` INTEGER NOT NULL,
    `coeft` DECIMAL(10, 4) NULL,
    `departmentId` BIGINT UNSIGNED NOT NULL,
    `organizationId` BIGINT UNSIGNED NOT NULL,
    `updateUserId` BIGINT UNSIGNED NOT NULL,
    `updateTime` DATETIME(3) NOT NULL,
    `expandProperties` JSON NOT NULL,
    `tagIds` JSON NOT NULL,
    `resourceLink` JSON NOT NULL,
    `labelNames` JSON NOT NULL,
    `lazyLoadFlags` JSON NOT NULL,
    `resourceWorkLocationList` JSON NOT NULL,
    `vehicleType` VARCHAR(32) NULL,
    `vehicleTypeName` VARCHAR(100) NOT NULL,
    `vehicleTypeDisplayOrder` INTEGER NOT NULL DEFAULT 100,
    `calculatedRelatedResourceId` BIGINT UNSIGNED NULL,
    `bindRelatedResourceId` BIGINT UNSIGNED NULL,
    `bindRelatedResourceId1` BIGINT UNSIGNED NULL,
    `bindRelatedResourceName` VARCHAR(100) NULL,
    `bindRelatedResourceDisplayName` VARCHAR(100) NULL,
    `calculatedRelatedResourceName` VARCHAR(100) NOT NULL,
    `calculatedRelatedResourceDisplayName` VARCHAR(100) NOT NULL,
    `allVehicle` JSON NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `syncedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `resources_code_key`(`code`),
    INDEX `resources_airportCode_resourceCategoryCode_resourceStatus_idx`(`airportCode`, `resourceCategoryCode`, `resourceStatus`),
    INDEX `resources_resourceGroupId_idx`(`resourceGroupId`),
    INDEX `resources_displayed_displayOrder_idx`(`displayed`, `displayOrder`),
    INDEX `resources_relatedExternalId_idx`(`relatedExternalId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
