-- CreateTable
CREATE TABLE `assignments` (
    `id` BIGINT UNSIGNED NOT NULL,
    `taskId` BIGINT UNSIGNED NOT NULL,
    `taskTypeId` BIGINT NOT NULL,
    `way` INTEGER NOT NULL,
    `currentResourceId` BIGINT UNSIGNED NOT NULL,
    `currentResourceCode` VARCHAR(32) NOT NULL,
    `currentResourceName` VARCHAR(255) NOT NULL,
    `currentResourceDisplayName` VARCHAR(255) NOT NULL,
    `currentResourceExternalId` VARCHAR(64) NOT NULL,
    `currentResourceGroupId` BIGINT NOT NULL,
    `currentRelatedResourceId` BIGINT NOT NULL,
    `currentRelatedResourceName` VARCHAR(255) NOT NULL,
    `currentRelatedResourceOther` VARCHAR(255) NOT NULL,
    `currentRelatedResourceOther2` VARCHAR(255) NOT NULL,
    `currentRelatedResourceOther3` VARCHAR(255) NOT NULL,
    `currentRelatedResourceOther4` VARCHAR(255) NOT NULL,
    `currentRelatedResourceLinkId` BIGINT NULL,
    `currentShiftDailyId` BIGINT UNSIGNED NOT NULL,
    `notifyStatus` INTEGER NOT NULL,
    `businessType` INTEGER NOT NULL,
    `departmentId` BIGINT NOT NULL,
    `organizationId` BIGINT NOT NULL,
    `updateUserId` BIGINT NOT NULL,
    `updateTime` DATETIME(3) NOT NULL,
    `createTime` DATETIME(3) NOT NULL,
    `createUserId` BIGINT NOT NULL,
    `deleted` BOOLEAN NOT NULL,
    `lastRelatedResourceId` BIGINT NULL,
    `lastRelatedResourceName` VARCHAR(255) NULL,

    INDEX `assignments_taskId_deleted_idx`(`taskId`, `deleted`),
    INDEX `assignments_currentResourceId_deleted_idx`(`currentResourceId`, `deleted`),
    INDEX `assignments_currentShiftDailyId_idx`(`currentShiftDailyId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `flights` (
    `id` BIGINT UNSIGNED NOT NULL,
    `flightNum` VARCHAR(32) NOT NULL,
    `flightDate` DATETIME(3) NOT NULL,
    `flightMissionProperty` VARCHAR(32) NOT NULL,
    `aircraft` VARCHAR(32) NOT NULL,
    `aircraftIata` VARCHAR(32) NOT NULL,
    `intDomType` VARCHAR(32) NOT NULL,
    `isRegionFlight` BOOLEAN NOT NULL,
    `vipFlag` INTEGER NOT NULL,
    `ioFlag` VARCHAR(32) NOT NULL,
    `arrivalAirport` VARCHAR(32) NOT NULL,
    `departureAirport` VARCHAR(32) NOT NULL,
    `sta` DATETIME(3) NOT NULL,
    `eta` DATETIME(3) NOT NULL,
    `ata` DATETIME(3) NOT NULL,
    `std` DATETIME(3) NOT NULL,
    `atd` DATETIME(3) NOT NULL,
    `registrationNumber` VARCHAR(32) NOT NULL,
    `bodyType` VARCHAR(32) NOT NULL,
    `aircraftClass` VARCHAR(32) NOT NULL,
    `fleetType` VARCHAR(32) NOT NULL,
    `standId` BIGINT NOT NULL,
    `standName` VARCHAR(255) NOT NULL,
    `standType` VARCHAR(32) NOT NULL,
    `standAreaId` BIGINT NOT NULL,
    `standAreaName` VARCHAR(255) NOT NULL,
    `selfTaxiStand` BOOLEAN NOT NULL,
    `standApronId` BIGINT NOT NULL,
    `standApronCode` VARCHAR(32) NOT NULL,
    `standApronName` VARCHAR(255) NOT NULL,
    `airportRunway` VARCHAR(32) NOT NULL,
    `terminalBuilding` VARCHAR(32) NOT NULL,
    `terminalBuildingId` BIGINT NOT NULL,
    `baggageCarouselName` VARCHAR(255) NOT NULL,
    `baggageTurntableName` VARCHAR(255) NOT NULL,
    `flightStatus` INTEGER NOT NULL,
    `hasDomPaxIntFlight` BOOLEAN NOT NULL,
    `serviceTypeCode` VARCHAR(32) NOT NULL,
    `airportCode` VARCHAR(32) NOT NULL,
    `airlineCode` VARCHAR(32) NOT NULL,
    `airlineIcaoCode` VARCHAR(32) NOT NULL,
    `isStopover` BOOLEAN NOT NULL,
    `flightRoute` VARCHAR(32) NOT NULL,
    `flightRouteCn` VARCHAR(32) NOT NULL,
    `uniqueId` VARCHAR(64) NOT NULL,
    `relatedExternalId` VARCHAR(64) NOT NULL,
    `isPlanCancel` BOOLEAN NOT NULL,
    `updateUserId` BIGINT NOT NULL,
    `updateTime` DATETIME(3) NOT NULL,
    `tagIds` JSON NOT NULL,
    `expandProperties` JSON NOT NULL,
    `boardFirstPaxNum` INTEGER NOT NULL,
    `boardClubPaxNum` INTEGER NOT NULL,
    `boardEcoPaxNum` INTEGER NOT NULL,
    `firstPaxNum` INTEGER NOT NULL,
    `clubPaxNum` INTEGER NOT NULL,
    `ecoPaxNum` INTEGER NOT NULL,
    `boardCipPaxNum` INTEGER NOT NULL,
    `cipPaxNum` INTEGER NOT NULL,
    `boardSuperCipPaxNum` INTEGER NOT NULL,
    `superCipPaxNum` INTEGER NOT NULL,
    `ecoClassCipPaxNum` INTEGER NOT NULL,
    `highClassCipPaxNum` INTEGER NOT NULL,
    `boardHighClassCipPaxNum` INTEGER NOT NULL,
    `boardEcoClassCipPaxNum` INTEGER NOT NULL,
    `boardPaxNum` INTEGER NOT NULL,
    `paxNum` INTEGER NOT NULL,
    `pnrFirstPaxNum` INTEGER NOT NULL,
    `pnrClubPaxNum` INTEGER NOT NULL,
    `pnrEcoPaxNum` INTEGER NOT NULL,
    `pnrHighClassCipPaxNum` INTEGER NOT NULL,
    `pnrEcoClassCipPaxNum` INTEGER NOT NULL,
    `pnrSpecialServicePaxNum` INTEGER NOT NULL,
    `pnrThroughPaxNum` INTEGER NOT NULL,
    `pnrUnaccompaniedPaxNum` INTEGER NOT NULL,
    `cpaxFirstPaxNum` INTEGER NOT NULL,
    `cpaxClubPaxNum` INTEGER NOT NULL,
    `cpaxEcoPaxNum` INTEGER NOT NULL,
    `cpaxHighClassCipPaxNum` INTEGER NOT NULL,
    `cpaxEcoClassCipPaxNum` INTEGER NOT NULL,
    `cpaxSpecialServicePaxNum` INTEGER NOT NULL,
    `cpaxThroughPaxNum` INTEGER NOT NULL,
    `cpaxUnaccompaniedPaxNum` INTEGER NOT NULL,
    `cpaxBaggageWeight` INTEGER NOT NULL,
    `cpaxBaggageNum` INTEGER NOT NULL,
    `passengerDataSource` VARCHAR(32) NOT NULL,
    `locationAreaName` VARCHAR(255) NOT NULL,
    `arrivalAirportShortName` VARCHAR(255) NOT NULL,
    `departureAirportShortName` VARCHAR(255) NOT NULL,
    `middleAirportShortName` VARCHAR(255) NOT NULL,
    `firstDeparturePaxNum` INTEGER NOT NULL,
    `clubDeparturePaxNum` INTEGER NOT NULL,
    `ecoDeparturePaxNum` INTEGER NOT NULL,
    `departurePaxNum` INTEGER NOT NULL,
    `specialServicePaxNum` INTEGER NOT NULL,
    `throughPaxNum` INTEGER NOT NULL,
    `firstBaggageWeight` INTEGER NOT NULL,
    `clubBaggageWeight` INTEGER NOT NULL,
    `ecoBaggageWeight` INTEGER NOT NULL,
    `baggageWeight` INTEGER NOT NULL,
    `baggageNum` INTEGER NOT NULL,
    `unaccompaniedPaxNum` INTEGER NOT NULL,
    `cpaxNumInfo` VARCHAR(32) NOT NULL,
    `pnrPaxNumInfo` VARCHAR(32) NOT NULL,
    `paxNumInfo` VARCHAR(32) NOT NULL,
    `ecoClassCipPaxNumInfo` VARCHAR(32) NOT NULL,
    `pilotMemberNum` INTEGER NOT NULL,
    `cabinMemberNum` INTEGER NOT NULL,
    `takeCrewMemberNum` INTEGER NOT NULL,
    `variableTaxiTime` INTEGER NOT NULL,
    `estTaxiInTime` DATETIME(3) NOT NULL,
    `actTaxiInTime` DATETIME(3) NOT NULL,
    `crewOwner` VARCHAR(32) NOT NULL,
    `cabinOwner` VARCHAR(32) NOT NULL,
    `carouselNo` VARCHAR(32) NOT NULL,
    `chuteNo` VARCHAR(32) NOT NULL,
    `conveyorNo` VARCHAR(32) NOT NULL,
    `domConn` BOOLEAN NOT NULL,
    `intConn` BOOLEAN NOT NULL,
    `calculatedIntDomType` VARCHAR(32) NOT NULL,
    `estimatedTime` DATETIME(3) NOT NULL,
    `domGateId` BIGINT NULL,
    `domGateName` VARCHAR(255) NULL,
    `domDebarkationSpotType` VARCHAR(32) NULL,
    `linkedFlightNum` VARCHAR(32) NULL,
    `linkedFlightNumPassStationTimeMinute` INTEGER NULL,
    `linkedFlightRelatedExternalId` VARCHAR(64) NULL,
    `linkedFlightSta` DATETIME(3) NULL,
    `linkedFlightEta` DATETIME(3) NULL,
    `linkedFlightAta` DATETIME(3) NULL,
    `linkedFlightStd` DATETIME(3) NULL,
    `linkedFlightAtd` DATETIME(3) NULL,
    `calcTakeOffTime` DATETIME(3) NULL,
    `calcOffBlockTime` DATETIME(3) NULL,

    INDEX `flights_airportCode_flightDate_idx`(`airportCode`, `flightDate`),
    INDEX `flights_flightNum_flightDate_idx`(`flightNum`, `flightDate`),
    UNIQUE INDEX `flights_uniqueId_key`(`uniqueId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `shift_daily` (
    `id` BIGINT UNSIGNED NOT NULL,
    `shiftDate` DATETIME(3) NOT NULL,
    `dailyOnOff` INTEGER NOT NULL,
    `shiftId` BIGINT NOT NULL,
    `shiftName` VARCHAR(255) NOT NULL,
    `patternId` BIGINT NOT NULL,
    `manual` BOOLEAN NOT NULL,
    `leadin` BOOLEAN NOT NULL,
    `resourceId` BIGINT UNSIGNED NOT NULL,
    `resourceGroupId` BIGINT NOT NULL,
    `relatedResourceId` BIGINT NOT NULL,
    `relatedResourceTypeCode` VARCHAR(32) NOT NULL,
    `scheduleShiftStartTime` DATETIME(3) NOT NULL,
    `scheduleShiftEndTime` DATETIME(3) NOT NULL,
    `estimatedShiftStartTime` DATETIME(3) NOT NULL,
    `estimatedShiftEndTime` DATETIME(3) NOT NULL,
    `actualStartTime` DATETIME(3) NOT NULL,
    `actualEndTime` DATETIME(3) NOT NULL,
    `startTime` VARCHAR(32) NULL,
    `endTime` VARCHAR(32) NULL,
    `isCrossDay` BOOLEAN NOT NULL,
    `backup` BOOLEAN NOT NULL,
    `actualAttendanceType` INTEGER NOT NULL,
    `actualAttendanceStatus` INTEGER NOT NULL,
    `actualLeaveType` INTEGER NOT NULL,
    `actualCardRecordStatus` INTEGER NOT NULL,
    `locationAreaId` BIGINT NOT NULL,
    `overtimeCode` VARCHAR(32) NOT NULL,
    `overtimeReason` TEXT NOT NULL,
    `leaveCode` VARCHAR(32) NOT NULL,
    `leaveReason` TEXT NOT NULL,
    `businessType` INTEGER NOT NULL,
    `departmentId` BIGINT NOT NULL,
    `organizationId` BIGINT NOT NULL,
    `updateUserId` BIGINT NOT NULL,
    `updateTime` DATETIME(3) NOT NULL,
    `leaveTimeVoList` JSON NOT NULL,
    `calculatedStartTime` DATETIME(3) NOT NULL,
    `calculatedEndTime` DATETIME(3) NOT NULL,

    INDEX `shift_daily_resourceId_scheduleShiftStartTime_scheduleShiftE_idx`(`resourceId`, `scheduleShiftStartTime`, `scheduleShiftEndTime`),
    INDEX `shift_daily_shiftDate_idx`(`shiftDate`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tasks` (
    `id` BIGINT UNSIGNED NOT NULL,
    `taskName` VARCHAR(255) NOT NULL,
    `taskDate` DATETIME(3) NOT NULL,
    `estimatedPrepareTime` INTEGER NOT NULL,
    `estimatedStartTimeInMinutes` INTEGER NULL,
    `estimatedEndTimeInMinutes` INTEGER NULL,
    `actualStartTime` DATETIME(3) NULL,
    `actualEndTime` DATETIME(3) NULL,
    `schedulePrepareTime` INTEGER NOT NULL,
    `scheduleStartTime` DATETIME(3) NOT NULL,
    `scheduleEndTime` DATETIME(3) NOT NULL,
    `scheduleDuration` INTEGER NOT NULL,
    `scheduleTravelTime` INTEGER NOT NULL,
    `estimatedStartTripTime` DATETIME(3) NULL,
    `estimatedStartTripTimeInMinutes` INTEGER NULL,
    `estimatedTravelTime` INTEGER NOT NULL,
    `actualStartTripTime` DATETIME(3) NULL,
    `scheduled` BOOLEAN NULL,
    `fromLocationId` BIGINT NULL,
    `toLocationId` BIGINT NULL,
    `fromLocation` VARCHAR(255) NULL,
    `toLocation` VARCHAR(255) NULL,
    `fromLocationTypeCode` VARCHAR(255) NULL,
    `toLocationTypeCode` VARCHAR(255) NULL,
    `fromLocationAreaId` BIGINT NULL,
    `taskTypeId` BIGINT NOT NULL,
    `taskGroupType` INTEGER NOT NULL,
    `taskRuleCategory` VARCHAR(32) NOT NULL,
    `priority` INTEGER NOT NULL,
    `weight` INTEGER NOT NULL,
    `taskCredit` INTEGER NOT NULL,
    `taskCreditRatio` INTEGER NOT NULL,
    `mustDispatch` BOOLEAN NOT NULL,
    `selfModifiedFlag` INTEGER NOT NULL,
    `locked` BOOLEAN NOT NULL,
    `appJudgeStatus` VARCHAR(32) NOT NULL,
    `taskStatus` INTEGER NOT NULL,
    `taskStatusChangeTime` DATETIME(3) NOT NULL,
    `splitted` BOOLEAN NOT NULL,
    `splittedFlag` INTEGER NOT NULL,
    `source` INTEGER NOT NULL,
    `taskSequenceNumber` INTEGER NOT NULL,
    `taskSequenceFlag` INTEGER NOT NULL,
    `isWorkTask` BOOLEAN NOT NULL,
    `isReservedTask` BOOLEAN NULL,
    `notifyStatus` INTEGER NOT NULL,
    `notifyTime` DATETIME(3) NULL,
    `notifyAckTime` DATETIME(3) NULL,
    `processFlag` INTEGER NOT NULL,
    `baseQualifications` VARCHAR(32) NULL,
    `baseRelatedQualifications` VARCHAR(32) NOT NULL,
    `flightId` BIGINT NOT NULL,
    `taskTime` DATETIME(3) NOT NULL,
    `lastTaskTime` DATETIME(3) NOT NULL,
    `parentId` BIGINT NOT NULL,
    `fromLocationArea` VARCHAR(255) NULL,
    `toLocationIntDomType` VARCHAR(255) NULL,
    `expandProperties` JSON NOT NULL,
    `tagIds` JSON NOT NULL,
    `currentResourceId` BIGINT NULL,
    `currentResourceName` VARCHAR(255) NULL,
    `currentResourceDisplayName` VARCHAR(255) NULL,
    `currentRelatedResourceId` BIGINT NULL,
    `currentRelatedResourceName` VARCHAR(255) NULL,
    `currentRelatedResourceDisplayName` VARCHAR(255) NULL,
    `currentRelatedResourceOther2` VARCHAR(255) NULL,
    `oldResourceDisplayName` VARCHAR(255) NULL,
    `oldRelatedResourceDisplayName` VARCHAR(255) NULL,
    `taskAssignUserId` BIGINT NULL,
    `taskAssignUserName` VARCHAR(255) NULL,
    `taskAssignUpdateTime` DATETIME(3) NULL,
    `taskAssignCreateUserId` BIGINT NULL,
    `taskAssignCreateUserName` VARCHAR(255) NULL,
    `taskAssignCreateTime` DATETIME(3) NULL,
    `flightNum` VARCHAR(32) NULL,
    `flightIntDomType` VARCHAR(32) NULL,
    `flightIoFlag` VARCHAR(32) NULL,
    `businessType` INTEGER NOT NULL,
    `departmentId` BIGINT NOT NULL,
    `organizationId` BIGINT NOT NULL,
    `updateUserId` BIGINT NOT NULL,
    `updateUserName` VARCHAR(255) NOT NULL,
    `updateTime` DATETIME(3) NOT NULL,
    `createUserId` BIGINT NOT NULL,
    `createUserName` VARCHAR(255) NOT NULL,
    `createTime` DATETIME(3) NOT NULL,
    `bodyType` VARCHAR(32) NULL,
    `aircraftClass` VARCHAR(32) NULL,
    `taskTypeName` VARCHAR(255) NOT NULL,
    `inFlightId` BIGINT NOT NULL,
    `outFlightId` BIGINT NOT NULL,
    `terminalBuilding` VARCHAR(32) NULL,
    `inFlightNum` VARCHAR(32) NULL,
    `inFlightDate` DATETIME(3) NULL,
    `inFlightIntDomType` VARCHAR(32) NULL,
    `inFlightAircraft` VARCHAR(32) NULL,
    `inFlightAircraftIata` VARCHAR(32) NULL,
    `relatedFlightId` BIGINT NOT NULL,
    `inBoundFlightDate` DATETIME(3) NULL,
    `inBoundSta` DATETIME(3) NULL,
    `inBoundEta` DATETIME(3) NULL,
    `inBoundAta` DATETIME(3) NULL,
    `inBoundStd` DATETIME(3) NULL,
    `inBoundAtd` DATETIME(3) NULL,
    `inBoundIoFlag` VARCHAR(32) NULL,
    `inBoundFlightStatus` INTEGER NULL,
    `inBoundFlightMissionProperty` VARCHAR(32) NULL,
    `inBoundStandName` VARCHAR(255) NULL,
    `inBoundStandType` VARCHAR(32) NULL,
    `inBoundStandApronId` BIGINT NULL,
    `inBoundStandApronName` VARCHAR(255) NULL,
    `inBoundStandApronCode` VARCHAR(32) NULL,
    `inBoundBodyType` VARCHAR(32) NULL,
    `inBoundAircraft` VARCHAR(32) NULL,
    `inBoundAircraftIata` VARCHAR(32) NULL,
    `inBoundRegistrationNumber` VARCHAR(32) NULL,
    `inBoundFirstDeparturePaxNum` INTEGER NULL,
    `inBoundClubDeparturePaxNum` INTEGER NULL,
    `inBoundEcoDeparturePaxNum` INTEGER NULL,
    `inBoundDeparturePaxNum` INTEGER NULL,
    `inBoundSpecialServicePaxNum` INTEGER NULL,
    `inBoundThroughPaxNum` INTEGER NULL,
    `inBoundFirstBaggageWeight` INTEGER NULL,
    `inBoundClubBaggageWeight` INTEGER NULL,
    `inBoundEcoBaggageWeight` INTEGER NULL,
    `inBoundBaggageWeight` INTEGER NULL,
    `inBoundUnaccompaniedPaxNum` INTEGER NULL,
    `taskRegistrationNumber` VARCHAR(32) NULL,
    `haveRemark` BOOLEAN NOT NULL,
    `deleted` BOOLEAN NOT NULL,
    `grabOrder` BOOLEAN NOT NULL,
    `calculatedStartTime` DATETIME(3) NOT NULL,
    `calculatedEndTime` DATETIME(3) NOT NULL,
    `calculatedFromLocation` VARCHAR(255) NULL,
    `calculatedToLocation` VARCHAR(255) NULL,
    `calculatedIntDomType` VARCHAR(32) NULL,
    `fromLocationManual` VARCHAR(255) NULL,
    `toLocationManual` VARCHAR(255) NULL,
    `taskCancelTime` DATETIME(3) NULL,
    `relatedExternalSourceId` VARCHAR(32) NULL,
    `description` TEXT NULL,
    `sourceTaskId` BIGINT NULL,
    `isReportedTask` BOOLEAN NULL,
    `fleetType` VARCHAR(32) NULL,
    `outFlightNum` VARCHAR(32) NULL,
    `outFlightDate` DATETIME(3) NULL,
    `outFlightIntDomType` VARCHAR(32) NULL,
    `outFleetType` VARCHAR(32) NULL,
    `outBoundFlightDate` DATETIME(3) NULL,
    `outBoundSta` DATETIME(3) NULL,
    `outBoundEta` DATETIME(3) NULL,
    `outBoundStd` DATETIME(3) NULL,
    `outBoundAtd` DATETIME(3) NULL,
    `outBoundIoFlag` VARCHAR(32) NULL,
    `outBoundFlightStatus` INTEGER NULL,
    `outBoundFlightMissionProperty` VARCHAR(32) NULL,
    `outBoundStandName` VARCHAR(255) NULL,
    `outBoundStandType` VARCHAR(32) NULL,
    `outBoundStandApronId` BIGINT NULL,
    `outBoundStandApronName` VARCHAR(255) NULL,
    `outBoundStandApronCode` VARCHAR(32) NULL,
    `outBoundBodyType` VARCHAR(32) NULL,
    `outBoundAircraft` VARCHAR(32) NULL,
    `outBoundAircraftIata` VARCHAR(32) NULL,
    `outBoundRegistrationNumber` VARCHAR(32) NULL,
    `outBoundFirstDeparturePaxNum` INTEGER NULL,
    `outBoundClubDeparturePaxNum` INTEGER NULL,
    `outBoundEcoDeparturePaxNum` INTEGER NULL,
    `outBoundDeparturePaxNum` INTEGER NULL,
    `outBoundSpecialServicePaxNum` INTEGER NULL,
    `outBoundThroughPaxNum` INTEGER NULL,
    `outBoundFirstBaggageWeight` INTEGER NULL,
    `outBoundClubBaggageWeight` INTEGER NULL,
    `outBoundEcoBaggageWeight` INTEGER NULL,
    `outBoundBaggageWeight` INTEGER NULL,
    `outBoundUnaccompaniedPaxNum` INTEGER NULL,
    `allowBoardingTime` DATETIME(3) NULL,
    `doorCloseTime` DATETIME(3) NULL,
    `inFleetType` VARCHAR(32) NULL,
    `toLocationAreaId` BIGINT NULL,
    `toLocationArea` VARCHAR(255) NULL,
    `fromLocationIntDomType` VARCHAR(255) NULL,
    `outFlightAircraft` VARCHAR(32) NULL,
    `outFlightAircraftIata` VARCHAR(32) NULL,
    `outBoundEtd` DATETIME(3) NULL,
    `baseQualificationIds` VARCHAR(32) NULL,
    `baseRelatedQualificationIds` VARCHAR(32) NULL,
    `inBoundEtd` DATETIME(3) NULL,

    INDEX `tasks_flightId_scheduleStartTime_idx`(`flightId`, `scheduleStartTime`),
    INDEX `tasks_taskDate_taskStatus_idx`(`taskDate`, `taskStatus`),
    INDEX `tasks_scheduleStartTime_scheduleEndTime_idx`(`scheduleStartTime`, `scheduleEndTime`),
    INDEX `tasks_taskTypeId_idx`(`taskTypeId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `assignments` ADD CONSTRAINT `assignments_taskId_fkey` FOREIGN KEY (`taskId`) REFERENCES `tasks`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `assignments` ADD CONSTRAINT `assignments_currentResourceId_fkey` FOREIGN KEY (`currentResourceId`) REFERENCES `resources`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `assignments` ADD CONSTRAINT `assignments_currentShiftDailyId_fkey` FOREIGN KEY (`currentShiftDailyId`) REFERENCES `shift_daily`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `shift_daily` ADD CONSTRAINT `shift_daily_resourceId_fkey` FOREIGN KEY (`resourceId`) REFERENCES `resources`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
